name: CI/CD Pipeline for Kubernetes

on:
#  push:
#    branches:
#      - main  # Trigger the pipeline on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.6

    # 3. Configure Google Cloud
    - name: Set up Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v0.8.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_CREDENTIALS_JSON }}
        region: us-central1

    # 4. Initialize Terraform and Apply
    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve

    # 5. Set up kubectl to connect to the GKE cluster
    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials my-cluster --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

    # 6. Deploy to Kubernetes (deploy the app)
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s/nginx/nginx-deployment.yaml
        kubectl apply -f ./k8s/nginx/nginx-service.yaml
        kubectl apply -f ./k8s/nginx/nginx-ingress.yaml
        kubectl apply -f ./k8s/app/app-deployment.yaml
        kubectl apply -f ./k8s/app/app-service.yaml

    # 7. Verify Deployment
    - name: Check Deployment Status
      run: |
        kubectl get deployments
        kubectl get pods
        kubectl get services
        kubectl get ingress
