name: CI/CD Pipeline for Kubernetes

on:
 push:
   branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'  

    - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2      
        with:
          project_id: ${{ secrets.PROJECT_ID }}

    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/test/js-app:1.0.0 .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/test/js-app:1.0.0 

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials gke-test-1 --region us-central1 --project ${{ secrets.PROJECT_ID }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s/nginx/nginx-deployment.yaml
        kubectl apply -f ./k8s/nginx/nginx-service.yaml
        kubectl apply -f ./k8s/nginx/nginx-ingress.yaml
        kubectl apply -f ./k8s/app/app-deployment.yaml
        kubectl apply -f ./k8s/app/app-service.yaml

    - name: Verify Deployment
      run: |
        kubectl get deployments
        kubectl get pods
        kubectl get services
        kubectl get ingress
